// ─────────────────────────────────────────────────────────
//  merge-schema.js
//  Gộp tất cả *.prisma trong prisma/schema/ vào prisma/schema.prisma
//  Chạy: node prisma/merge-schema.js
// ─────────────────────────────────────────────────────────
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname);
const SCHEMA_DIR = path.join(ROOT, "schema");
const TARGET = path.join(ROOT, "schema.prisma");

// ── 1. Header: datasource + generator (luôn giữ nguyên) ──
const header = `// ─────────────────────────────────────────────────────────
//  AUTO-GENERATED — Do NOT edit this file directly.
//  Edit the individual files in prisma/schema/ instead,
//  then run:  npm run prisma:merge
// ─────────────────────────────────────────────────────────

generator client {
  provider = "prisma-client"
  output   = "../generated/prisma"
}

datasource db {
  provider = "postgresql"
}
`;

// ── 2. Đọc & sắp xếp các file model ──
// Thứ tự: enums trước, rồi theo alphabet (để quan hệ luôn hợp lệ)
const files = fs
  .readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith(".prisma"))
  .sort((a, b) => {
    // enums luôn đứng đầu
    if (a === "enums.prisma") return -1;
    if (b === "enums.prisma") return 1;
    return a.localeCompare(b);
  });

if (files.length === 0) {
  console.error("❌ No .prisma files found in prisma/schema/");
  process.exit(1);
}

// ── 3. Gộp nội dung ──
const merged = files
  .map((f) => {
    const content = fs.readFileSync(path.join(SCHEMA_DIR, f), "utf8").trim();
    return `// ═══ Source: schema/${f} ═══\n${content}`;
  })
  .join("\n\n");

// ── 4. Ghi ra schema.prisma ──
const output = `${header}\n${merged}\n`;
fs.writeFileSync(TARGET, output, "utf8");

console.log(`✅ Merged ${files.length} files → prisma/schema.prisma`);
files.forEach((f) => console.log(`   • schema/${f}`));
