import { Product } from "@/types/product";

export const products: Product[] = [
    {
        id: 1,
        title: "Zessi Dresses",
        category: "Dress",
        price: 99,
        rating: 5,
        reviews: "1.2k+",
        image: "/product_list/product_0-1.jpg",
        images: [
            "/product_list/product_0-1.jpg",
            "/product_list/product_0-2.jpg",
        ],
        colors: ["Yellow", "White", "Black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 2,
        title: "Kirby T-Shirt",
        category: "T-Shirt",
        price: 45,
        rating: 4,
        reviews: "800+",
        image: "/product_list/product_1-1.jpg",
        images: [
            "/product_list/product_1-1.jpg",
            "/product_list/product_1.jpg",
        ],
        colors: ["Blue", "Grey"],
        sizes: ["M", "L", "XL"],
    },
    {
        id: 3,
        title: "Cobleknit Shawl",
        category: "Shawl",
        price: 120,
        rating: 5,
        reviews: "3.5k+",
        image: "/product_list/product_2-1.jpg",
        images: [
            "/product_list/product_2-1.jpg",
            "/product_list/product_2.jpg",
        ],
        colors: ["Beige", "Brown"],
        sizes: ["One Size"],
    },
    {
        id: 4,
        title: "Floral Maxi Dress",
        category: "Dress",
        price: 150,
        rating: 5,
        reviews: "2k+",
        image: "/product_list/product_3-1.jpg",
        images: [
            "/product_list/product_3-1.jpg",
            "/product_list/product_3.jpg",
        ],
        colors: ["Pink", "Green"],
        sizes: ["S", "M", "L"],
    },
    {
        id: 5,
        title: "Classic Denim Jacket",
        category: "Jacket",
        price: 85,
        rating: 4,
        reviews: "5k+",
        image: "/product_list/product_4-1.jpg",
        images: [
            "/product_list/product_4-1.jpg",
            "/product_list/product_4.jpg",
        ],
        colors: ["Denim Blue"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 6,
        title: "Silk Scarf",
        category: "Accessory",
        price: 30,
        rating: 5,
        reviews: "1k+",
        image: "/product_list/product_5-1.jpg",
        images: [
            "/product_list/product_5-1.jpg",
            "/product_list/product_5.jpg",
        ],
        colors: ["Red", "Purple"],
        sizes: ["One Size"],
    },
    {
        id: 7,
        title: "Ribbed Tank Top",
        category: "Tops",
        price: 25,
        rating: 4,
        reviews: "500+",
        image: "/product_list/product_6-1.jpg",
        images: [
            "/product_list/product_6-1.jpg",
            "/product_list/product_6.jpg",
        ],
        colors: ["White"],
        sizes: ["S", "M", "L"],
    },
    {
        id: 8,
        title: "Zip-up Hoodie",
        category: "Hoodies",
        price: 55,
        rating: 5,
        reviews: "1.5k+",
        image: "/product_list/product_7-1.jpg",
        images: [
            "/product_list/product_7-1.jpg",
            "/product_list/product_7.jpg",
        ],
        colors: ["Grey"],
        sizes: ["M", "L", "XL", "XXL"],
    },
    {
        id: 9,
        title: "Polka Dot Dress",
        category: "Dress",
        price: 135,
        rating: 5,
        reviews: "900+",
        image: "/product_list/product_8-1.jpg",
        images: [
            "/product_list/product_8-1.jpg",
            "/product_list/product_8.jpg",
        ],
        colors: ["Black"],
        sizes: ["S", "M", "L"],
    },
    {
        id: 10,
        title: "Long Sleeve Tee",
        category: "T-Shirt",
        price: 40,
        rating: 4,
        reviews: "2.1k+",
        image: "/product_list/product_9-1.jpg",
        images: [
            "/product_list/product_9-1.jpg",
            "/product_list/product_9.jpg",
        ],
        colors: ["Black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 11,
        title: "Slim Fit Polo",
        category: "Polo",
        price: 50,
        rating: 5,
        reviews: "1.8k+",
        image: "/product_list/product_10-1.jpg",
        images: [
            "/product_list/product_10-1.jpg",
            "/product_list/product_10.jpg",
        ],
        colors: ["Blue"],
        sizes: ["S", "M", "L", "XL"],
    },
];
