version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    # Giới hạn tài nguyên để chạy nhẹ nhất có thể
    deploy:
      resources:
        limits:
          memory: 64M
    # Vô hiệu hóa persistence nếu chỉ dùng làm cache để giảm I/O
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  redis_data:
