@baseUrl = http://localhost:5000/api/v1

### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "password123",
    "fullName": "Test User",
    "phone": "0123456789"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

### Get Current User Profile
@token = {{login.response.body.data.accessToken}}
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
